config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: :show
    resources :categories, only: :show, param: :taxon_id
    resources :suggests, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def self.prepended(base)
    # variant  Spree::Variantクラス
    # max_related_products 関連商品の最大表示数
    base.scope :init_related_products, ->(variant, max_related_products) do
      base.includes([master: [:images, :default_price]]).
        in_taxons(variant.product.taxon_ids).
        distinct.where.not(id: variant.id).sample(max_related_products)
    end
  end
  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:taxon_id])
    @taxon_roots = Spree::Taxon.roots
    @taxon_all_products = @taxon.all_products.includes([master: [:images, :default_price]])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @variant = Spree::Product.find(params[:id]).variants_including_master.find(params[:id])

    @default_taxon_id = Spree::Taxon.first.presence&.id

    @related_products = Spree::Product.init_related_products(@variant, Potepan::MAX_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/suggests_controller.rb
class Potepan::SuggestsController < ApplicationController
  def index
    search_params = params[:keyword]

    if bad_request?(search_params)
      render(json: { message: "search word error" }, status: 400)
      return
    end

    client = HTTPClient.new
    url = ENV['SEARCH_WEBAPI_URL']
    header = { 'Authorization' => ENV['SEARCH_WEBAPI_KEY'] }
    query = {
      'keyword' => search_params,
      'max_num' => Potepan::MAX_SUGGESTS_NUM,
    }
    res = client.get(url, query, header)
    if res.status == 200
      render json: JSON.parse(res.body)
    else
      render json: { message: "#{url} API error" }, status: res.status
    end
  end

  private

  def bad_request?(search_params)
    search_params.empty?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # page title
  def full_title(page_title)
    base_title = 'BIGBAG Store'
    if page_title.blank?
      "#{base_title}"
    else
      "#{page_title} - #{base_title}"
    end
  end

  def product_image(product)
    if product.master.images.present?
      image_tag(product.master.images.first.attachment(:large), alt: "#{product.name}-img")
    else
      image_tag("img/products/products-01.jpg", alt: "#{product.name}-img")
    end
  end
end

app/views/layouts/_footer.html.slim
/ FOOTER
/ COPY RIGHT
#footer.copyRight.clearfix
  .container
    .row
      .col-sm-7.col-xs-12
        p
          | © 2016-
          = Time.current.year
          |  Copyright Potepan Store .
      .col-sm-5.col-xs-12
        ul.list-inline
          li
            a[href="#"]
              i.fa.fa-twitter
          li
            a[href="#"]
              i.fa.fa-facebook

app/views/layouts/_header.html.slim
/ HEADER
.header.clearfix
  / TOPBAR
  .topBar
    .container
      .row
        .col-md-6.hidden-sm.hidden-xs
          ul.list-inline
            li
              a[href="#"]
                i.fa.fa-twitter
            li
              a[href="#"]
                i.fa.fa-facebook
        .col-md-6.col-xs-12
          ul.list-inline.pull-right
            li.dropdown.searchBox
              a.dropdown-toggle[href="javascript:void(0)" data-toggle="dropdown"]
                i.fa.fa-search
              ul.dropdown-menu.dropdown-menu-right
                form#form01[action="product-grid-left-sidebar.html" method="post"]
                  li
                    span.input-group
                      input#search-form.form-control.get_suggest.ui-autocomplete-input aria-describedby="basic-addon2" autocomplete="off" name="searchWord" placeholder="Search…" type="text"
                      span#basic-addon2.input-group-addon.addPointer[onclick="FormSubmit();"]
                        | 検索
            li.dropdown
              a.dropdown-toggle[href="cart-page.html" data-toggle="dropdown disabled"]
                i.fa.fa-shopping-cart
  / NAVBAR
  nav.navbar.navbar-main.navbar-default[role="navigation"]
    .container
      .navbar-header
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse"]
          span.sr-only
            | Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to  image_tag("logo.png"), potepan_index_path, class: "navbar-brand"
      .collapse.navbar-collapse.navbar-ex1-collapse
        ul.nav.navbar-nav.navbar-right
          li.active
            a[href="javascript:void(0)"]
              | Home
          li.dropdown.megaDropMenu
            a.dropdown-toggle[href="javascript:void(0)" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false"]
              | Shop

app/views/layouts/_login_modal.html.slim
/ LOGIN MODAL
#login.modal.fade.login-modal[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        h3.modal-title
          | ログイン
      .modal-body
        form[action="login-" method="POST" role="form"]
          .form-group
            label[for="login-email"]
              | メールアドレス
            input#login-email.form-control[type="email"]
          .form-group
            label[for="login-password"]
              | パスワード
            input#login-password.form-control[type="password"]
          .checkbox
            label
              input[type="checkbox"]
              |  記憶しておく 
          button.btn.btn-primary.btn-block[type="submit"]
            | ログイン
          a.btn.btn-link.btn-block[href="lost-password.html"]
            | パスワードをお忘れの方

app/views/layouts/_page_header.html.slim
section.lightSection.clearfix.pageHeader
  .container
    .row
      .col-xs-6
        .page-title
          h2= title_name
      .col-xs-6
        ol.breadcrumb.pull-right
          li
            = link_to 'Home', potepan_index_path
          li
            a[href="#"]
              | shop
          li.active= title_name

app/views/layouts/_quick_view_modal.html.slim
/ PORDUCT QUICK VIEW MODAL
.modal.fade.quick-view[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-body
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        .media
          .media-left
            = image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image")
          .media-body
            h2
              | Old Skool Navy
            h3
              | 149円
            p
              | Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.
            span.quick-drop
              select#guiest_id3.select-drop[name="guiest_id3"]
                option[value="0"]
                  | S
                option[value="1"]
                  | M
                option[value="2"]
                  | L
                option[value="3"]
                  | XL
            span.quick-drop.resizeWidth
              select#guiest_id4.select-drop[name="guiest_id4"]
                / option[value="0"]
                  | 数
                option[value="1"]
                  | 1
                option[value="2"]
                  | 2
                option[value="3"]
                  | 3
            .btn-area
              a.btn.btn-primary.btn-block[href="cart_page.html"]
                | カートへ入れる 
                i.fa.fa-angle-right[aria-hidden="true"]

app/views/layouts/_signup_modal.html.slim
/ SIGN UP MODAL
#signup.modal.fade[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        h3.modal-title
          | 新規登録
      .modal-body
        form[action="" method="POST" role="form"]
          .form-group
            label[for="signup-email"]
              | メールアドレス
            input#signup-email.form-control[type="email"]
          .form-group
            label[for="signup-password"]
              | パスワード
            input#signup-password.form-control[type="password"]
          .form-group
            label[for="signup-password-confirmation"]
              | パスワード（確認用）
            input#signup-password-confirmation.form-control[type="password"]
          button.btn.btn-primary.btn-block[type="submit"]
            | 登録する

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all"    

    / ! CUSTOM CSS
    / ! HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / ! WARNING: Respond.js doesn't work if you view the page via file://
    / ![if lt IE 9]
    script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js" 
    script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js" 

  body
    .main-wrapper
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'
    = render 'layouts/login_modal'
    = render 'layouts/signup_modal'
    = render 'layouts/quick_view_modal'

    = javascript_include_tag 'application'

app/views/potepan/categories/_category_panel.html.slim
.panel.panel-default
  .panel-heading
    | 商品カテゴリー
  .panel-body
    .collapse.navbar-collapse.navbar-ex1-collapse.navbar-side-collapse
      ul.nav.navbar-nav.side-nav
        - taxon_roots.each do |root|
          li
            a[href="javascript:;" data-toggle="collapse" data-target="#taxon_root_#{root.id}"]
              = root.name
              i.fa.fa-plus
            ul.collapse.collapseItem id=("taxon_root_#{root.id}")
              - root.leaves.each do |leaf|                        
                li
                  = link_to potepan_category_path(leaf.id)
                    i.fa.fa-caret-right[aria-hidden="true"]
                    = leaf.name
                    span
                      = "(#{leaf.products.count})"

app/views/potepan/categories/_color_panel.html.slim
.panel.panel-default.filterNormal
  .panel-heading
    | 色から探す
  .panel-body
    ul.list-unstyled
      li
        a[href="#"]
          | ブラック
          span
            | (15)
      li
        a[href="#"]
          | ホワイト
          span
            | (10)
      li
        a[href="#"]
          | レッド
          span
            | (7)
      li
        a[href="#"]
          | ブルー
          span
            | (12)
      li
        a[href="#"]
          | オレンジ
          span
            | (12)

app/views/potepan/categories/_filter_area.html.slim
.row.filterArea
  .col-xs-6
    select#guiest_id1.select-drop[name="guiest_id1"]
      option[value="0"]
        | 並び替え
      option[value="1"]
        | 人気順
      option[value="2"]
        | 安い順
      option[value="3"]
        | 新着順
      option[value="3"]
        | 高い順
  .col-xs-6
    .btn-group.pull-right[role="group"]
      button.btn.btn-default.active[type="button" onclick="window.location.href='product_grid_left_sidebar.html'"]
        i.fa.fa-th[aria-hidden="true"]
        span
          | Grid
      button.btn.btn-default[type="button" onclick="window.location.href='product_list_left_sidebar.html'"]
        i.fa.fa-th-list[aria-hidden="true"]
        span
          | List

app/views/potepan/categories/_partners_logo_slider.html.slim
.owl-carousel.partnersLogoSlider
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-01.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-02.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-03.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-04.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-05.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-01.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-02.png", :alt => "partner-img")
  .slide
    .partnersLogo.clearfix
      = image_tag("img/home/partners/partner-03.png", :alt => "partner-img")

app/views/potepan/categories/_sidebar.html.slim
= render 'category_panel', taxon_roots: taxon_roots
= render 'color_panel'
= render 'size_panel'

app/views/potepan/categories/_size_panel.html.slim
.panel.panel-default.filterNormal
  .panel-heading
    | サイズから探す
  .panel-body
    ul.list-unstyled.clearfix
      li
        a[href="#"]
          | S
          span
            | (15)
      li
        a[href="#"]
          | M
          span
            | (10)
      li
        a[href="#"]
          | L
          span
            | (7)
      li
        a[href="#"]
          | XL
          span
            | (12)

app/views/potepan/categories/show.html.slim
- provide(:title, @taxon.name)
= render 'layouts/page_header', title_name: @taxon.name
/ MAIN CONTENT SECTION
section.mainContent.clearfix.productsContent
  .container
    .row
      .col-md-3.col-sm-4.col-xs-12.sideBar
        = render 'sidebar', taxon_roots: @taxon_roots
      .col-md-9.col-sm-8.col-xs-12
        = render 'filter_area'
        .row
          - @taxon_all_products.each do |product|
            .col-sm-4.col-xs-12
              .productBox
                = link_to potepan_product_path(product.id)
                  .productImage.clearfix
                    = product_image(product)
                  .productCaption.clearfix
                    h5= product.name
                    h3= product.display_price.to_s
/ LIGHT SECTION
section.lightSection.clearfix
  .container
    .row
      .col-xs-12
        = render 'partners_logo_slider'

app/views/potepan/products/_link_to_categories.html.slim
- if variant.product.taxons.present?
  = link_to potepan_category_path(variant.product.taxons.first.id)
    | 一覧ページへ戻る
    i.fa.fa-reply[aria-hidden="true"]
- elsif default_taxon_id.present?
  = link_to potepan_category_path(default_taxon_id)
    | 一覧ページへ戻る
    i.fa.fa-reply[aria-hidden="true"]
- else
  = link_to potepan_index_path
    | トップページへ戻る
    i.fa.fa-reply[aria-hidden="true"]

app/views/potepan/products/_related_products.html.slim
.row.productsContent
  .col-xs-12
    .page-header
      h4
        | 関連商品
  - related_products.each do |product|
    .col-md-3.col-sm-6.col-xs-12
      .productBox
        = link_to potepan_product_path(product.id)
          .productImage.clearfix
            = product_image(product)
          .productCaption.clearfix
            h5= product.name
            h3= product.display_price

app/views/potepan/products/show.html.slim
- provide(:title, @variant.name)
= render 'layouts/page_header', title_name: @variant.name
section.mainContent.clearfix
  .container
    .row.singleProduct
      .col-xs-12
        .media
          .media-left.productSlider
            #carousel.carousel.slide[data-ride="carousel"]
              .carousel-inner
                - @variant.gallery.images.each_with_index do |image, i|
                  .item class=('active' if i.zero?) data-thumb="#{i}"
                    = image_tag(image.attachment(:large))
            .clearfix
              #thumbcarousel.carousel.slide[data-interval="false"]
                .carousel-inner
                  - @variant.gallery.images.each_with_index do |image, i|
                    .thumb[data-target="#carousel" data-slide-to="#{i}"]
                      = image_tag(image.attachment(:small))
                a.left.carousel-control[href="#thumbcarousel" role="button" data-slide="prev"]
                  span.glyphicon.glyphicon-chevron-left
                a.right.carousel-control[href="#thumbcarousel" role="button" data-slide="next"]
                  span.glyphicon.glyphicon-chevron-right
          .media-body
            ul.list-inline
              li
                = render 'link_to_categories', variant: @variant, default_taxon_id: @default_taxon_id
            h2= @variant.name
            h3= @variant.display_price
            p= @variant.description
            span.quick-drop
              select#guiest_id3.select-drop[name="guiest_id3"]
                option[value="0"]
                  | S
                option[value="1"]
                  | M
                option[value="2"]
                  | L
                option[value="3"]
                  | XL
            span.quick-drop.resizeWidth
              select#guiest_id4.select-drop[name="guiest_id4"]
                option[value="1"]
                  | 1
                option[value="2"]
                  | 2
                option[value="3"]
                  | 3
            .btn-area
              a.btn.btn-primary.btn-block[href="cart_page.html"]
                | カートへ入れる
                i.fa.fa-angle-right[aria-hidden="true"]
    = render 'related_products', related_products: @related_products

app/views/potepan/sample/cart_page.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      | Cart Page - BIGBAG Store
    = stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all"
  body
    .main-wrapper
      .header.clearfix
        .topBar
          .container
            .row
              .col-md-6.hidden-sm.hidden-xs
                ul.list-inline
                  li
                    a[href="#"]
                      i.fa.fa-twitter
                  li
                    a[href="#"]
                      i.fa.fa-facebook
              .col-md-6.col-xs-12
                ul.list-inline.pull-right
                  li
                    span
                      a[data-toggle="modal" href="#login"]
                        | Log in
                      small
                        | or
                      a[data-toggle="modal" href="#signup"]
                        | Create an account
                  li.dropdown.searchBox
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      i.fa.fa-search
                    ul.dropdown-menu.dropdown-menu-right
                      li
                        span.input-group
                          input.form-control[type="text" placeholder="Search…" aria-describedby="basic-addon2"]
                          span#basic-addon2.input-group-addon
                            | Search
                  li.dropdown
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      i.fa.fa-shopping-cart
                    ul.dropdown-menu.dropdown-menu-right
                      li
                        | Item(s) in your cart
                      li
                        a[href="#"]

                        .media
                          = image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image")
                          .media-body
                            h5.media-heading
                              | INCIDIDUNT UT 
                              br
                              span
                                | 2 X $199
                      li
                        a[href="#"]

                        .media
                          = image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image")
                          .media-body
                            h5.media-heading
                              | INCIDIDUNT UT 
                              br
                              span
                                | 2 X $199
                      li
                        .btn-group[role="group" aria-label="..."]
                          button.btn.btn-default[type="button"]
                            | Shopping Cart
                          button.btn.btn-default[type="button"]
                            | Checkout
        nav.navbar.navbar-main.navbar-default[role="navigation"]
          .container
            .navbar-header
              button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse"]
                span.sr-only
                  | Toggle navigation
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand[href="index.html"]
                = image_tag("img/logo.png", :alt => "")
            .collapse.navbar-collapse.navbar-ex1-collapse
              ul.nav.navbar-nav.navbar-right
                li
                  a[href="index.html"]
                    | Home
                li.dropdown.megaDropMenu.active
                  a.dropdown-toggle[href="javascript:void(0)" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false"]
                    | Shop
      section.lightSection.clearfix.pageHeaderImage
        .container
          .tableBlock
            .row.tableInner
              .col-xs-12
                .page-title
                  h2
                    | cart
                  ol.breadcrumb
                    li
                      a[href="index.html"]
                        | Home
                    li.active
                      | cart
      section.mainContent.clearfix.cartListWrapper
        .container
          .row
            .col-xs-12
              .cartListInner
                form[action="#"]
                  .table-responsive
                    table.table
                      thead
                        tr
                          th
                          th
                            | 商品名
                          th
                            | 価格
                          th
                            | 数
                          th
                            | 小計
                      tbody
                        tr
                          td.col-xs-2
                            button.close[type="button" data-dismiss="alert" aria-label="Close"]
                              span[aria-hidden="true"]
                                | ×
                            span.cartImage
                              = image_tag("img/products/cart-image.jpg", :alt => "image")
                          td.col-xs-4
                            | Italian Winter Hat
                          td.col-xs-2
                            | 99円
                          td.col-xs-2
                            input[type="text" placeholder="1"]
                          td.col-xs-2
                            | 99円
                        tr
                          td.col-xs-2
                            button.close[type="button" data-dismiss="alert" aria-label="Close"]
                              span[aria-hidden="true"]
                                | ×
                            span.cartImage
                              = image_tag("img/products/cart-image.jpg", :alt => "image")
                          td.col-xs-4
                            | Italian Winter Hat
                          td.col-xs-2
                            | 99円
                          td.col-xs-2
                            input[type="text" placeholder="1"]
                          td.col-xs-2
                            | 99円
                        tr
                          td.col-xs-2
                            button.close[type="button" data-dismiss="alert" aria-label="Close"]
                              span[aria-hidden="true"]
                                | ×
                            span.cartImage
                              = image_tag("img/products/cart-image.jpg", :alt => "image")
                          td.col-xs-4
                            | Italian Winter Hat
                          td.col-xs-2
                            | 99円
                          td.col-xs-2
                            input[type="text" placeholder="1"]
                          td.col-xs-2
                            | 99円
                  .updateArea
                    a.btn[href="#"]
                      | アップデート
                  .totalAmountArea
                    .col-sm-4.col-sm-offset-8.col-xs-12
                      ul.list-unstyled
                        li
                          | 小計 
                          span
                            | 792円
                        li
                          | 消費税 
                          span
                            | 18円
                        li
                          | 総計 
                          span.grandTotal
                            | 810円
                  .checkBtnArea
                    a.btn.btn-primary.btn-block[href="checkout_step_1.html"]
                      | 購入する
                      i.fa.fa-arrow-circle-right[aria-hidden="true"]
      #footer.copyRight.clearfix
        .container
          .row
            .col-sm-7.col-xs-12
              p
                | © 2016-
                = Time.now.year
                |  Copyright Potepan Store .
            .col-sm-5.col-xs-12
              ul.list-inline
                li
                  a[href="#"]
                    i.fa.fa-twitter
                li
                  a[href="#"]
                    i.fa.fa-facebook
    #login.modal.fade[tabindex="-1" role="dialog"]
      .modal-dialog
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-hidden="true"]
              | ×
            h3.modal-title
              | log in
          .modal-body
            form[action="" method="POST" role="form"]
              .form-group
                label[for="login-email"]
                  | Enter Email
                input#login-email.form-control[type="email"]
              .form-group
                label[for="login-password"]
                  | Password
                input#login-password.form-control[type="password"]
              .checkbox
                label
                  input[type="checkbox"]
                  |  Remember Me 
              button.btn.btn-primary.btn-block[type="submit"]
                | log in
              button.btn.btn-link.btn-block[type="button"]
                | Forgot Password?
    #signup.modal.fade[tabindex="-1" role="dialog"]
      .modal-dialog
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-hidden="true"]
              | ×
            h3.modal-title
              | Create an account
          .modal-body
            form[action="" method="POST" role="form"]
              .form-group
                label[for="signup-email"]
                  | Enter Email
                input#signup-email.form-control[type="email"]
              .form-group
                label[for="signup-password"]
                  | Password
                input#signup-password.form-control[type="password"]
              .form-group
                label[for="signup-password-confirmation"]
                  | Confirm Password
                input#signup-password-confirmation.form-control[type="password"]
              button.btn.btn-primary.btn-block[type="submit"]
                | Sign up